### ISSUE TITLE
FormElementMixin is not defined

### ISSUE THREAD

**Issue by ACTLEM** [fooloomanzoo/input-picker-pattern#1]
When we try to use a number-input (via the time-picker), we got the following issue: FormElementMixin is not defined. It looks like a problem of scope. As we try to use this component in a project with webpack, the FormElementMixin is put in other file so its scope is not accessible from number-input.

In form-element-mixin.html, a simple fix could be to add it in the window scope like this:
```
<script>
...
window.FormElementMixin = FormElementMixin
</script>
```

In fact, the problem is present for all Mixin elements, DatetimeInputMixin, IntegerInputMixin, NumberInputMixin...

Thanks a lot for the fix.

**Comment by fooloomanzoo** [comment]
Why do you thank me before I have fixed it? Or do you think that I owe you personally something?

**Comment by PonyLux** [comment]
Got the same issue here.

Don't know why you use `html` file to define a Javascript module...

As I can see you expose the Mixin on the `window` which is ugly IMO.
Couldn't we use Javascript export functionality ?

**Comment by tverhoken** [comment]
Common @fooloomanzoo , your reaction here is a bit defensive.

I think the point here is to know if mixins declaration is good or not.

In fact, we saw that some of other files in this repo assigned to `window` their declarations but not `FormElementMixin` which cause trouble when using it with Webpack bundler (and maybe without bundler).

Another question is that is it really necessary to have html import when there's only a `script` tag in it ? Maybe it could be better to put that on a `.js` file and do some UMD packaging which will allow using it everywhere.

I think we will be happy to do changes but we wanna have your advice on it first because you created this repo.

What do you think ?

**Comment by fooloomanzoo** [comment]
Did you even have used Polymer before? There are good reasons to not use Html Imports anymore, but because Polymer has an own building system, and there not really good and easy to handle alternatives and until Polymer 3 is not a release candidate, so that it is clear how it will integrate with other ES6 modules, I don't see a reason to break with the actual eco system or the style. It would just be unnecessary and vain endeavor. But when it is more clear, the elements will be transformed
