### ISSUE TITLE
Performance on IE

### ISSUE THREAD

**Issue by schrotie** [fooloomanzoo/input-picker-pattern#3]
Hello again!

I had opened a pull-request one or two weeks ago because of a width-initialization loop. You successfully resolved this in a different way.
Now I was analyzing a performance regression on IE (from 7s to 20s initial load/render time) and found that it was input-picker-pattern. I did not debug deep enough to find where the performance goes (because that is a lot of work in IE 11 where the profiler crashes a soon as I turn it on). But I found that I have 72 instances of input-picker-pattern on my page (legit, nothing wrong with input-picker-pattern). However, my profiling showed that the resize method alone takes 9 seconds of pure processing time and I guess the rest is somewhere else.
I was able to fix my issue without touching your code (by only rendering the date-pickers when the respective pop-ups are shown). You may close this issue, just wanted to let you know.

    Cheers

**Comment by fooloomanzoo** [comment]
Now there is a different method taken for resizing, that clones a sizing Element (in InputPattern). I also can not use the profiler in IE because it delays massively but if not turned on it seems to work stable and performant. It might has something to do with babeling the files and how IE reacts on that. Would be good to know how it looks now. Regards
